set nocompatible

syntax on

set expandtab
set tabstop=8

" set autoindent
" set cindent
" set shiftwidth=4

set statusline=%t\ [%L\ lines]\ [%{&ff}]\ %=\ [%04l,%04v]\ [%p%%]
set laststatus=2

set backspace=indent,eol,start

set number
set numberwidth=5

colors wombat256

autocmd Bufwritepre,filewritepre *.c,*.h exe "1," . 10 . "g/Aenderungsdatum:.*/s/Aenderungsdatum:.*/Aenderungsdatum:     " .strftime("%c")

